quarkus:
  application:
    name: gestion-juridica-back
    version: 1.0-SNAPSHOT

  http:
    port: ${PORT:10000}
    host: 0.0.0.0
    cors:
      enabled: true
      origins: "${CORS_ORIGINS:http://localhost:4200}"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Content-Type,Authorization,X-Requested-With,Origin,Accept

  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${JDBC_DATABASE_URL}
    devservices:
      enabled: false

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true

  log:
    level: INFO
    console:
      enabled: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
    file:
      enabled: false

  swagger-ui:
    always-include: true
    path: /swagger-ui

  smallrye-openapi:
    path: /openapi

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: "Gestion juridica"
          version: "1.1.0"