quarkus:
  datasource:
    db-kind: h2
    username: admin
    password: 12345
    jdbc:
      url: jdbc:h2:mem:gestion_juridica_dev;DB_CLOSE_DELAY=-1

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true

  http:
    cors:
      enabled: true
      origins: "*"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Content-Type,Authorization,X-Requested-With,Origin,Accept

  swagger-ui:
    always-include: true
